apiVersion: v1
kind: Service
metadata: 
    name: flask-change-service
spec:
    selector:
        app: python-flask
    ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
    type: LoadBalancer
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: python-flask
spec:
    selector:
        mathLabels:
            app: python-flask
    replicas: 3
    template:
        metadata:
            labels:
                app: python-flask
        spec:
            containers:
            - name: flask-change
              image: flask-change:latest
              imagePullPolicy: Never
              ports:
              - containerPort: 8080